### ISSUE TITLE
New rules?

### ISSUE THREAD

**Issue by hankhero** [peturh/swedish-newspaper-fixer#2] opened 2017-03-30 17:43 UTC
Now not working for me on this article: http://www.dn.se/kultur-noje/fredrik-strage-jag-har-overvagt-att-jk-anmala-peter-springare-for-kulturell-appropriering/

Issue seems to be this (new?) rule.
Maybe remove .article__body--mask classes will solve it? I don't have recent skills to make plugin, just an idea.

.article__body--mask .article__premium-content {
    /* display: none; */
}

**Comment by peturh** [comment] 2017-03-31 06:16
I tried the page (and I actually read that article today) and it works on my machine and I'm unable to reproduce. Can you maybe screen shot the DOM-structure or something to show me what elements are blocking the article.

**Comment by peturh** [comment] 2017-03-31 08:47
I've been digging a bit into this. 

Are you sure that you sent the correct link? I noticed that mobil.dn.se did not work. Did you maybe access that domain?

Another alternative is that some other resource did not finish loading, usually some ad or something. And since I run the little script on `document_end`, the document never ends to load and the paywall still exists. 

An ugly way to get around this is simply to press the "X" to the left of the address bar.

**Comment by hankhero** [comment] 2017-04-03 06:36
It was the right url, same thing happened twice, but then I did a refresh and suddenly it worked. Maybe some slow loading time thing indeed. Thanks for looking into this.

**Comment by peturh** [comment] 2017-04-03 09:05
Closing

**Closed as completed by peturh** 2017-04-03 09:05 UTC
